apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: myreactapp1
        image: abdimak/bestimg:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"  # Set the CPU limit to 0.5 cores
            memory: "512Mi"  # Set the memory limit to 512 megabytes
          requests:
            cpu: "0.1"  # Set the CPU request to 0.1 cores
            memory: "256Mi"  # Set the memory request to 256 megabytes
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-svc
spec:
  type: NodePort
  selector:
    app: my-react-app 
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
