apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: myreactapp1
        image: abdimak/bestimg:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-svc
spec:
  type: NodePort
  selector:
    app: my-react-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
