apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      -name: myreactapp1
       image: abdimak/bestimg:latest
---

apiVersion: v1
kind: Service
metadata:
  name: myapp-srv
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    